model: r1
editor-model: sonnet
architect: true
multiline: true
auto-commits: false
model-settings-file: .aider.model.setting.yml
alias:
  - r1:openrouter/deepseek/deepseek-r1
code-theme: monokai
user-input-color: "#c0caf5"
tool-output-color: "#9ece6a"
tool-error-color: "#f7768e"
tool-warning-color: "#e0af68"
assistant-output-color: "#7dcfff"
completion-menu-color: "#c0caf5"
completion-menu-bg-color: "#101119"
completion-menu-current-color: "#c0caf5"
completion-menu-current-bg-color: "#283457"
