model: sonnet
multiline: true
auto-commits: false
dark-mode: true
user-input-color: "#25be6a"
tool-output-color: "#dfdfe0"
tool-error-color: "#ee5396"
tool-warning-color: "#08bdba"
assistant-output-color: "#78a9ff"
completion-menu-color: "#f2f4f8"
completion-menu-bg-color: "#2b2b2b"
completion-menu-current-color: "#08bdba"
completion-menu-current-bg-color: "#353535"
