local palette = {
  bg = "#14151f",
  fg = "#c0caf5",
  fg_alt = "#828ab0",
  selection = "#283457",
  split = "#545c7e",
  tab_bar = "#333333",
  red = "#f7768e",
  red_bright = "#ff899d",
  green = "#9ece6a",
  yellow = "#e0af68",
  yellow_bright = "#faba4a",
  blue = "#7aa2f7",
  blue_bright = "#8db0ff",
  magenta = "#bb9af7",
  magenta_bright = "#c7a9ff",
  cyan = "#7dcfff",
  cyan_bright = "#a4daff",
}

return {
  foreground = palette.fg,
  background = palette.bg,
  cursor_bg = palette.fg,
  cursor_border = palette.fg,
  cursor_fg = palette.bg,
  selection_bg = palette.selection,
  split = palette.split,
  ansi = {
    palette.fg_alt,
    palette.red,
    palette.green,
    palette.yellow,
    palette.blue,
    palette.magenta,
    palette.cyan,
    palette.fg_alt,
  },
  brights = {
    palette.fg_alt,
    palette.red_bright,
    palette.green,
    palette.yellow_bright,
    palette.blue_bright,
    palette.magenta_bright,
    palette.cyan_bright,
    palette.fg_alt,
  },
  tab_bar = {
    inactive_tab_edge = palette.tab_bar,
  },
}
