[metadata]
name = "carbonfox"

[colors]
foreground = "#f2f4f8"
background = "#161616"
cursor_bg = "#f2f4f8"
cursor_border = "#f2f4f8"
cursor_fg = "#161616"
selection_bg = "#3b3b3b"
scrollbar_thumb = "#7b7c7e"
split = "#5e5e5e"

ansi = [
    "#9d9d9f",
    "#ee5396",
    "#25be6a",
    "#08bdba",
    "#78a9ff",
    "#be95ff",
    "#33b1ff",
    "#dfdfe0",
]

brights = [
    "#9d9d9f",
    "#f16da6",
    "#46c880",
    "#2dc7c4",
    "#8cb6ff",
    "#c8a5ff",
    "#52bdff",
    "#e4e4e5",
]
