[colors]
foreground = "#d8dee9"
background = "#1a1a1a"
cursor_bg = "#d8dee9"
cursor_border = "#d8dee9"
cursor_fg = "#1a1a1a"
selection_bg = "#303030"
split = "#505050"

ansi = [
    "#9a9dab",
    "#ff6464",
    "#83d6c5",
    "#eeb080",
    "#87c3ff",
    "#e394dc",
    "#87c3ff",
    "#9a9dab",
]

brights = [
    "#9a9dab",
    "#ff6464",
    "#83d6c5",
    "#eeb080",
    "#87c3ff",
    "#e394dc",
    "#87c3ff",
    "#9a9dab",
]
